name: simple_utils
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/koiralapankaj7/simple_utils.git

environment:
  sdk: ">=3.2.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter: null
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
